{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_origins",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_origins-1.0.0.jar",
          "url": "newnew_origins-1.0.0.jar",
          "size": 22589,
          "sha512": "3f4d01d3237a88dc485c6d10db9a49cc1c4cec7f29990f1a8972938ba6b9091395638824b69a77f507276864048331191048db533105c1494cd5638e99010643",
          "sha256": "70cc9d056e685a919f84ddfb50a9eb798c8fecf7e05133007011be6a9d102a87",
          "sha1": "27848745b643a2ffd248cfdc3dd0cac6aa67e0e0",
          "md5": "9ec7102af440918b8fe3fb0940dfcd5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.edwinmindcraft",
          "module": "apoli-forge",
          "version": {
            "strictly": "1.20.1-2.9.0.8_mapped_parchment_2023.09.03-1.20.1",
            "requires": "1.20.1-2.9.0.8_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "io.github.edwinmindcraft",
          "module": "calio-forge",
          "version": {
            "strictly": "1.20.1-1.11.0.5_mapped_parchment_2023.09.03-1.20.1",
            "requires": "1.20.1-1.11.0.5_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "io.github.edwinmindcraft",
          "module": "origins-forge",
          "version": {
            "strictly": "1.20.1-1.10.0.9_mapped_parchment_2023.09.03-1.20.1",
            "requires": "1.20.1-1.10.0.9_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "top.theillusivec4.caelus",
          "module": "caelus-forge",
          "version": {
            "strictly": "3.2.0+1.20.1_mapped_parchment_2023.09.03-1.20.1",
            "requires": "3.2.0+1.20.1_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_origins-1.0.0.jar",
          "url": "newnew_origins-1.0.0.jar",
          "size": 22589,
          "sha512": "3f4d01d3237a88dc485c6d10db9a49cc1c4cec7f29990f1a8972938ba6b9091395638824b69a77f507276864048331191048db533105c1494cd5638e99010643",
          "sha256": "70cc9d056e685a919f84ddfb50a9eb798c8fecf7e05133007011be6a9d102a87",
          "sha1": "27848745b643a2ffd248cfdc3dd0cac6aa67e0e0",
          "md5": "9ec7102af440918b8fe3fb0940dfcd5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "newnew_origins-1.0.0-sources.jar",
          "url": "newnew_origins-1.0.0-sources.jar",
          "size": 13043,
          "sha512": "2b77d4835cf0bb5803f07c5cc2a24e5bb559c6443a9a733a3cfae169298403dfe1bd962e19365be730043dab68b2eab9e27f67953c79ff1422562e8eb259e128",
          "sha256": "877d4220cf611a67f73669532c958b33f05ec9a54b46804b12c6c7b4aa9ebe22",
          "sha1": "b3b79b083e051dbf8c4dab451605a62e49c7cf3f",
          "md5": "35d1f02f0bb7576e491765a77f14bf99"
        }
      ]
    }
  ]
}
