{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_origins",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_origins-1.0.0.jar",
          "url": "newnew_origins-1.0.0.jar",
          "size": 21939,
          "sha512": "520e1ac923a20363fc504823fa298a5a9cb2c60c26ef7b154b9a959c76697205138a7d8ec56dc6856e3560c6a71cd937a63bbeecf6bbe7d0adc655867a064649",
          "sha256": "58ef05b3e3e9127ad0a4e71bdf72c6f54a28d39eb57de757d24952b6c54a7e7d",
          "sha1": "77d42e3976c624b2193ebb0292ed8437302b3a86",
          "md5": "f442c8fb6966f8449272762c396425f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.edwinmindcraft",
          "module": "apoli-forge",
          "version": {
            "strictly": "1.20.1-2.9.0.8_mapped_parchment_2023.09.03-1.20.1",
            "requires": "1.20.1-2.9.0.8_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "io.github.edwinmindcraft",
          "module": "calio-forge",
          "version": {
            "strictly": "1.20.1-1.11.0.5_mapped_parchment_2023.09.03-1.20.1",
            "requires": "1.20.1-1.11.0.5_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "io.github.edwinmindcraft",
          "module": "origins-forge",
          "version": {
            "strictly": "1.20.1-1.10.0.9_mapped_parchment_2023.09.03-1.20.1",
            "requires": "1.20.1-1.10.0.9_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "top.theillusivec4.caelus",
          "module": "caelus-forge",
          "version": {
            "strictly": "3.2.0+1.20.1_mapped_parchment_2023.09.03-1.20.1",
            "requires": "3.2.0+1.20.1_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_origins-1.0.0.jar",
          "url": "newnew_origins-1.0.0.jar",
          "size": 21939,
          "sha512": "520e1ac923a20363fc504823fa298a5a9cb2c60c26ef7b154b9a959c76697205138a7d8ec56dc6856e3560c6a71cd937a63bbeecf6bbe7d0adc655867a064649",
          "sha256": "58ef05b3e3e9127ad0a4e71bdf72c6f54a28d39eb57de757d24952b6c54a7e7d",
          "sha1": "77d42e3976c624b2193ebb0292ed8437302b3a86",
          "md5": "f442c8fb6966f8449272762c396425f2"
        }
      ]
    }
  ]
}
