{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_origins",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_origins-1.0.0.jar",
          "url": "newnew_origins-1.0.0.jar",
          "size": 22589,
          "sha512": "c4db0c6095561982cd02254c13d211af252ed6b8400da5e841b7770d45ee3e197659304c1465d5dcf512e6f7d7f495d67083caf6946d2ce58c4297a1a53aa6d5",
          "sha256": "0b75404b7c29be77403241151b1c6938858a375b50f1471f75734b4c69f5a4b3",
          "sha1": "51ef34e1062d1ec39cdb3382d814bbd99eba2894",
          "md5": "f8c60b9376eb49fec0778d7eb2e87269"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.edwinmindcraft",
          "module": "apoli-forge",
          "version": {
            "requires": "1.20.1-2.9.0.8"
          }
        },
        {
          "group": "io.github.edwinmindcraft",
          "module": "calio-forge",
          "version": {
            "requires": "1.20.1-1.11.0.5"
          }
        },
        {
          "group": "io.github.edwinmindcraft",
          "module": "origins-forge",
          "version": {
            "requires": "1.20.1-1.10.0.9"
          }
        },
        {
          "group": "top.theillusivec4.caelus",
          "module": "caelus-forge",
          "version": {
            "requires": "3.2.0+1.20.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_origins-1.0.0.jar",
          "url": "newnew_origins-1.0.0.jar",
          "size": 22589,
          "sha512": "c4db0c6095561982cd02254c13d211af252ed6b8400da5e841b7770d45ee3e197659304c1465d5dcf512e6f7d7f495d67083caf6946d2ce58c4297a1a53aa6d5",
          "sha256": "0b75404b7c29be77403241151b1c6938858a375b50f1471f75734b4c69f5a4b3",
          "sha1": "51ef34e1062d1ec39cdb3382d814bbd99eba2894",
          "md5": "f8c60b9376eb49fec0778d7eb2e87269"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "newnew_origins-1.0.0-sources.jar",
          "url": "newnew_origins-1.0.0-sources.jar",
          "size": 13043,
          "sha512": "2b77d4835cf0bb5803f07c5cc2a24e5bb559c6443a9a733a3cfae169298403dfe1bd962e19365be730043dab68b2eab9e27f67953c79ff1422562e8eb259e128",
          "sha256": "877d4220cf611a67f73669532c958b33f05ec9a54b46804b12c6c7b4aa9ebe22",
          "sha1": "b3b79b083e051dbf8c4dab451605a62e49c7cf3f",
          "md5": "35d1f02f0bb7576e491765a77f14bf99"
        }
      ]
    }
  ]
}
